import type { Product } from "@/components/cart-provider"

export const products: Product[] = [
  {
    id: 1,
    name: "Señuelo Crankbait Pro",
    price: 12.99,
    image: "/colorful-fishing-crankbait-lure.jpg",
    description: "Señuelo de buceo profundo ideal para lubinas y luciopercas. Acción realista y colores vibrantes.",
    category: "Crankbaits",
  },
  {
    id: 2,
    name: "Spinnerbait Dorado",
    price: 9.99,
    image: "/golden-spinnerbait-fishing-lure.jpg",
    description: "Spinnerbait con hojas doradas que crean vibraciones irresistibles. Perfecto para aguas turbias.",
    category: "Spinnerbaits",
  },
  {
    id: 3,
    name: "Jig Head Tungsteno",
    price: 7.99,
    image: "/tungsten-jig-head-fishing-lure.jpg",
    description: "Cabeza de jig de tungsteno de alta densidad. Hundimiento rápido y gran sensibilidad.",
    category: "Jigs",
  },
  {
    id: 4,
    name: "Topwater Popper",
    price: 11.99,
    image: "/topwater-popper-fishing-lure.jpg",
    description: "Señuelo de superficie con acción popper. Ideal para ataques explosivos al amanecer.",
    category: "Topwater",
  },
  {
    id: 5,
    name: "Soft Plastic Worm",
    price: 5.99,
    image: "/soft-plastic-worm-fishing-lure.jpg",
    description: "Gusano de plástico suave con aroma. Textura realista y movimiento natural en el agua.",
    category: "Soft Plastics",
  },
  {
    id: 6,
    name: "Swimbait Realista",
    price: 15.99,
    image: "/realistic-swimbait-fishing-lure.jpg",
    description: "Swimbait articulado con acabado ultra realista. Natación perfecta a cualquier velocidad.",
    category: "Swimbaits",
  },
  {
    id: 7,
    name: "Buzzbait Titanio",
    price: 10.99,
    image: "/titanium-buzzbait-fishing-lure.jpg",
    description: "Buzzbait con hélice de titanio. Crea una estela de burbujas irresistible en superficie.",
    category: "Buzzbaits",
  },
  {
    id: 8,
    name: "Jerkbait Suspending",
    price: 13.99,
    image: "/suspending-jerkbait-fishing-lure.jpg",
    description: "Jerkbait de suspensión con acción errática. Perfecto para pausas largas.",
    category: "Jerkbaits",
  },
  {
    id: 9,
    name: "Chatterbait Vibración",
    price: 8.99,
    image: "/chatterbait-vibrating-fishing-lure.jpg",
    description: "Chatterbait con paleta vibradora. Combina lo mejor de jigs y spinnerbaits.",
    category: "Chatterbaits",
  },
  {
    id: 10,
    name: "Frog Hollow Body",
    price: 9.49,
    image: "/hollow-body-frog-fishing-lure.jpg",
    description: "Rana de cuerpo hueco para vegetación densa. Anzuelos sin enganches.",
    category: "Frogs",
  },
  {
    id: 11,
    name: "Lipless Crankbait",
    price: 11.49,
    image: "/lipless-crankbait-fishing-lure.jpg",
    description: "Crankbait sin labio con sonajeros internos. Vibración intensa y versátil.",
    category: "Crankbaits",
  },
  {
    id: 12,
    name: "Tube Bait Finesse",
    price: 6.99,
    image: "/tube-bait-finesse-fishing-lure.jpg",
    description: "Tube bait para técnicas finesse. Ideal para pesca en aguas claras y presionadas.",
    category: "Soft Plastics",
  },
]

export const categories = [
  "Crankbaits",
  "Spinnerbaits",
  "Jigs",
  "Topwater",
  "Soft Plastics",
  "Swimbaits",
  "Buzzbaits",
  "Jerkbaits",
  "Chatterbaits",
  "Frogs",
]
